### ISSUE TITLE
[FEATURE] Post screenshot customizations

### ISSUE THREAD

**Issue by mngshm** [Mangeshrex/chitra#2]
This issue is to define the feature of doing the post screenshot customization. This is where chitra is supposed to do its work exactly how it is planned to. 

The customisations would:
1. Adding a black (option for 7 colors + Gradient option) through `Gtk.colorSelectionDialog`. 
2. Making all the color blocks clickable and applying that color as the background to the Image which is captured. This should take input from Maim capture straight. 
3. Feature for adding drop shadow. The shadow input for X and Y coordinate should be taken. The depth can also be taken from the user input.

The Wireframe:
![image](https://github.com/user-attachments/assets/ac62e661-8b2d-42a5-8436-277b073de2a5)

**Comment by YashReddy1963** [comment]
# https://github.com/YashReddy1963/chitra/pull/9
