### ISSUE TITLE
[FEATURE] Dialog menu for further actions on the customised screenshot

### ISSUE THREAD

**Issue by mngshm** [Mangeshrex/chitra#3]
After the user customizes the screenshot. There should be a confirm button at the bottom which will make the user see a dialog box with the below options: 

1. Upload to 0x0.st and get a link
2. Save to System (`path: ~/Pictures`). if save to system, the file manager or a dialog should appear to save the name of Image.
3. Copy to Clipboard (can use `xclip -selection clipboard` for this feature.

![image](https://github.com/user-attachments/assets/8641c9c0-4554-4399-a4d9-41d34bf759f3)

**Comment by YashReddy1963** [comment]
https://github.com/YashReddy1963/chitra/pull/9
