### ISSUE TITLE
[FEATURE] Taking screenshot with maim and python

### ISSUE THREAD

**Issue by mngshm** [Mangeshrex/chitra#7]
This is the core bottleneck feature. In future, if we find a better way, we can rewrite the screenshot part to work from scratch. For now, chitra will use maim as the screenshot capture tool. 

The feature is supposed to make use of maim to take screenshot and bind it to various buttons on the home screen display of the app: 
1. Take screenshot of the screen.
2. Select particular rectangular.

**Comment by YashReddy1963** [comment]
[# https://github.com/Mangeshrex/chitra/pull/8](https://github.com/Mangeshrex/chitra/pull/8)
